### PR TITLE
Set up Ionic app

### PR DESCRIPTION
**Pull request by johannaanden**
## Tasks
- Scaffolds Ionic application
- Removes unnecessary scaffolded code
- Adds Ionic lab

## Pivotal Tracker
[Link](https://www.pivotaltracker.com/story/show/163343954)

## Screenshot
screenshot 2019-01-22 at 09 53 34

screenshot 2019-01-22 at 09 53 56

### CODE REVIEW

**Review by CamronLDNF — APPROVED** [review]
Looks good!

**Review by shahin1290 — CHANGES_REQUESTED** [review]
Remove the comments from index.html

**Comment by johannaanden** [comment]
@shahin1290 We have cleaned up index.html now, we only kept the service worker.

**Review by oliverochman — APPROVED** [review]
LGTM!

**Pull request merged**
